title = "Портофлио"
baseURL = "https://mofrog.github.io/portfolio-site/"
languageCode = "ru-ru"
theme = "mlkw"

[params]
  description = "Ниже представлены различные мои проекты."
  author = "Александр Новиков"
  age = "19 лет"
  city = "г.Краснодар"